.gitignore
CMakeLists.txt
README.md
example/CMakeLists.txt
example/triangle.cpp
ext/CMakeLists.txt
src/VkBootstrap.h
tests/CMakeLists.txt
tests/main.cpp
tests/run_tests.cpp

Sorry about this big commit.
- Use Catch to do nested testing
- Make vulkan include path public so the tests and examples can find it
- Make compiler warnings an interface target so the tests and example can also use it

Migrate to Catch2 & CMake file structural change

---

CMakeLists.txt

I'm using clang++ on windows to compile my project. One of my submodules uses vk-bootstrap which has been updated by the maintainer recently. After updating the submodule the build failed with
```
[1/45] Building CXX object ext/vuk/ext/vk-bootstrap/CMakeFiles/vk-bootstrap.dir/src/VkBootstrap.cpp.obj
FAILED: ext/vuk/ext/vk-bootstrap/CMakeFiles/vk-bootstrap.dir/src/VkBootstrap.cpp.obj
C:\llvm\bin\clang++.exe   -I../ext/vuk/ext/vk-bootstrap/src -IC:/VulkanSDK/1.2.135.0/Include -g -Xclang -gcodeview -O0 -D_DEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrtd   /WX /W4 -std=gnu++2a -MD -MT ext/vuk/ext/vk-bootstrap/CMakeFiles/vk-bootstrap.dir/src/VkBootstrap.cpp.obj -MF ext\vuk\ext\vk-bootstrap\CMakeFiles\vk-bootstrap.dir\src\VkBootstrap.cpp.obj.d -o …
```

Fixed detection of clang++ on windows

---

CMakeLists.txt
docs/getting_started.md
example/CMakeLists.txt
src/VkBootstrap.cpp
src/VkBootstrap.h
tests/CMakeLists.txt
tests/bootstrap_tests.cpp
tests/common.h

Make vk-bootstrap capable of loading the vulkan runtime and not need to
link against the library. This improves the usability of vk-bootstrap since
now you don't need the vulkan library on your system to build.
This commit also changes how SystemInfo works so as to allow the dynamic
vulkan loading.
Closes #17

Dynamically load vulkan instead of statically link.

---

CMakeLists.txt

Fix several things in CMakeLists:
- vk-bootstrap requires C++14, not C++11
- libdl must be linked on Linux
Moreover, an install target is added.

Fix CMake build and add install target

---

.gitignore
src/VkBootstrap.cpp
src/VkBootstrap.h
tests/bootstrap_tests.cpp

Users can now ask for physical devices which support a specific 1.1 and 1.2
feature. VkBootstrap will then add the selected features to the enable list
in device creation.
Addresses #25

Add selection by and enableing 1.1 and 1.2 features.

---

README.md

Changed "it's" to "its" on README.md, under the "Setting up vk-bootstrap" section. I believe it is meant that the library depends on the standard library of C++14, not that it is a standard library itself.

Fixed a typo on README.md about dependencies

---

src/VkBootstrap.cpp
src/VkBootstrap.h

This comparison is a simple addition that proves helpful when the developer intends to use swapchain obtained images for cases like storage purposes.

Check desired surface formats against feature flags

---

.github/workflows/ci_build.yml
CMakeLists.txt
README.md

Warnings as errors are nice for developers of the project but not for consumers (simple user / package managers). Compilation could fail with new versions of compilers introducing new warnings.

CMake: add an option to enable warnings as errors

---

src/VkBootstrap.cpp
src/VkBootstrap.h
tests/bootstrap_tests.cpp

Recreated PR as breaking bug has been remedied.
This PR is a bit of an overhaul of how features are handled internally and mainly affects `DeviceBuilder` and `PhysicalDeviceSelector`.
I added a crude reflection container that handles ownership/matching/destruction of said containers specific features struct instance. Vectors of these containers are used in both device creation and in physical device selection to verify that the specific feature fields requested in the feature structs are properly supported by a device.
Awhile ago I had to hack in some explicit checks for specific descriptor indexing features. I decided to try and make a generic impl that would support all range of feature structures so that we don't have to explicitly create a specific chunk of logic for every possible …

Added generic feature polling/enabling.

---

.github/workflows/ci_build.yml
CMakeLists.txt
README.md

Reverts charles-lunarg/vk-bootstrap#61
Needs to get compilation working under Ubuntu

Revert "CMake: add an option to enable warnings as errors"

---

README.md

This provides better error messages when the target cannot be found

Use CMake namespaced target in CMake ReadMe

---

src/VkBootstrap.cpp
src/VkBootstrap.h
tests/CMakeLists.txt
tests/common.h
tests/unit_tests.cpp

Additionally adds comments on the constructors for SwapchainBuilder and resolves the TODO of when the swapchain builder constructor fails to get the queue indices.
Fixes #71

Refactor internal queue selection logic

---

src/VkBootstrap.cpp
src/VkBootstrap.h
tests/bootstrap_tests.cpp

Previously, vk-bootstrap didn't support calling vkGetPhyicalDeviceFeaturesKHR
on devices which support the extension. This makes vk-bootstrap more amenable
to 1.0 only hardware, like rasberry pi's.

Call KHR version of get phys dev properties if necessary

---

src/VkBootstrap.cpp
src/VkBootstrap.h
tests/bootstrap_tests.cpp

The vulkan-loader implements the debug utils extension and always makes it available.
So this change makes it so that vk-bootstrap will always enable the extension and setup a
debug callback.
In addition, it is now possible to set pUserData if the user desires, which is nice for
custom debug callbacks
Lastly, the location of the default debug messenger function is now in the header file,
which makes it easier to find and possibly edit.

Allow setting pUserData in Debug Messenger, move default callback to header file.

---

script/generate_dispatch.py
src/VkBootstrap.cpp
src/VkBootstrap.h
src/VkBootstrapDispatch.h

A small change has been made to GenericFeaturesPNextNode and the dispatch table now generates in UTF-8. This is mainly a requisite to a future PR I have planned.

Small changes To GenericFeaturesPNextNode and DispatchTable generation

---

CMakeLists.txt
example/CMakeLists.txt
tests/CMakeLists.txt

This is just a minor change to use vk-bootstrap with an install(export) setup in cmake.
The added "src" include path would contain CMAKE_SOURCE_DIR and that causes an error
message as it could not be exported into a cmake target config file.

fix minor typos and duplicate include paths

---

example/triangle.cpp
src/VkBootstrap.cpp
src/VkBootstrap.h
tests/bootstrap_tests.cpp

This adds [user-defined conversion](https://en.cppreference.com/w/cpp/language/cast_operator) operators to `Instance`, `Device`, `PhysicalDevice` and `Swapchain`. This basically means that one can simply pass any of the previously mentioned objects to any Vulkan function which accepts the Vulkan equivalent, say `VkInstance`, `VkDevice`, `VkPhysicalDevice`, and `VkSwapchainKHR` respectively. This would cut down on the need of getting the field each time and would be probably be a great enhancement, especially for Vulkan beginners.
I find it extremely painful to often be writing code like this (it also just seems a bit weird):
```cpp
vkb::Device device;
vkGetDeviceProcAddr(device.device, &addressInfo);
```
Now, to save just a few characters, I think it'd be nice if one could just write it …

Add user-defined conversion operators

---

CMakeLists.txt

This change seems to be required for this project to work as a [vcpkg port](https://github.com/spnda/vcpkg/tree/master/ports/vk-bootstrap) as it otherwise can't find `VkBootstrapDispatch.h` in any include path. I'm no CMake expert so I'm not quite sure why because this project already does `target_include_directories`, but if it works it works. And I don't think it would break anything else.

Fix: Add VkBootstrapDispatch to includable files

---

src/VkBootstrap.cpp
tests/bootstrap_tests.cpp

vk-bootstrap would attempt to call vkGetPhysDevFeaturesKHR without enabling the appropriate extension first.
Fixes #99

Fix crashing when calling GetPhysDevFeaturesKHR

---

CMakeLists.txt

Enable upstream scripts to install the `vk-boostrap-targets` export-set directly.
Close #105

CMake: export vk-bootstrap and dependent targets

---

script/generate_dispatch.py
src/VkBootstrapDispatch.h

The autogen accidentally took a reference instead of a copy, so all the aliases
were using the same data as the base type, leading to incorrect macro guards.
In addition, any aliased function would use the base funciton's types, leading
to incompatibilities when compiling with older headers. The chosen solution is
to always use the alias type if it exists.
Lastly, NVX was added to a blacklist, no functions from NVX extensions will be
generated, since they are experimental in nature.
Fixes #100

Fixup autogen script for 1.1

---

src/VkBootstrap.cpp
src/VkBootstrap.h

Allows apps to find all the extensions available. If they do not enable the layer the
extension comes from, the instance will fail creation due to missing the layer that
implements the extension.

Add extensions in layers to main list

---

src/VkBootstrap.cpp
src/VkBootstrap.h
tests/bootstrap_tests.cpp

The macros were used inconsistently used; sometimes `VK_API_VERSION_x_y`, sometimes `VK_VERSION_x_y`. I did not change the dispatch table, but they definitions could be re-used there too, as previously suggested in https://github.com/charles-lunarg/vk-bootstrap/issues/94#issuecomment-1031361373. And it should fix using older header versions where the `_API_` macros don't exist yet.

Use own Vulkan version macros

---

src/VkBootstrap.h

The version macro selector was looking for the constant VK_API_VERSION instead of the correct macro VK_MAKE_VERSION. Replaced the preprocessors accordingly.

Fix version macro not selecting VK_MAKE_VERSION

---

src/VkBootstrap.cpp
src/VkBootstrap.h
tests/bootstrap_tests.cpp

Allows applications to desire_api_version that is
higher than available instance version.
It is possible to use PhysicalDevices with newer api version as long as your Instance is at least 1.1.
However application **must** not use newer api features if ApplicationInfo.apiVersion is set to lower value. ( [Vk spec Chap4. #VkApplicationInfo](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/chap4.html#VkApplicationInfo) )
This PR allows one to create instance with lower version while keeping ApplicationInfo::apiVersion at desired value

Allow desiring higher api versions

---

src/VkBootstrap.cpp
src/VkBootstrap.h
tests/bootstrap_tests.cpp

Adds an overload to `vkb::swapchain::get_image_views` to support passing a `pNext` chain.
Closes #122

Added pNext chain support for swapchain::get_image_views

---

src/VkBootstrap.cpp

c543dc1 introduced support for `VK_KHR_portability_enumeration`, but macro guard around the usage of `VK_INSTANCE_CREATE_ENUMERATE_PORTABILITY_BIT_KHR` seems to have been forgotten, which made the program not compile for older header versions.

Fix c543dc1: portability_enumeration flag was not available before 1.3.208

---

src/VkBootstrap.cpp

When using an API version other than VK 1.0 (read 1.1 and higher), we should use the functionality in core rather than the extension for getting the device physical properties.  This resolves the output produced by the best practices layer.

Fix best practices warning when in VK 1.1 or higher

---

src/VkBootstrap.cpp
src/VkBootstrap.h

Hi,
It is as the title says; my use cases are : 
- I wanted a feature to get the present mode actually used for the swapchain, so I could display an indicator in my application;
- I wanted to easily get the value of `create_info.minImageCount`, to confirm (and display) whether or not we're likely in a double-buffering setup or triple-buffering setup. I know this does not prove anything, but I think it is interesting even as a hint.
Thanks for considering this, as always I am open to any feedback.

SwapchainBuilder: expose present_mode and requested_min_image_count in the resulting Swapchain

---

src/VkBootstrap.cpp

Simple adjustment to the `desired_flags` logical test. Wouldn't change any existing functionality, but would cover future use cases if the given parameter was more than a single bit (e.g., two or more combined flags).

Fix #129 with correct desired_flags test

---

script/generate_dispatch.py
src/VkBootstrapDispatch.h

Some alias types are not pure promotional types, and need to be excluded from the
code which replaces types with their alias.
This may be a stopgap solution for a larger underlying problem of not being able to
determine if an alias is promoted or not.
When I tested this change with the 1.3.211 SDK installed, it compiled successfully whereas before it printed the error messages with `VkPipelineInfoEXT`.
This is a competing solution to #146

Add exclusion list for alias in generator code

---

src/VkBootstrap.cpp

The second argument to erase is exclusive, so we want to use `.end()` directly; otherwise we'll either fail to remove the very last element (if the range is non-empty) or crash (if `partition_index` is `physical_devices.end()`).

Fix crash during removal of unsuitable physical devices when using only_fully_suitable selection mode

---

src/VkBootstrap.cpp
src/VkBootstrap.h

This just passes through the final color space used after finding a suitable surface format to the user so it can be queried later.

Expose the final color space used when creating swapchains

---

script/generate_dispatch.py
src/VkBootstrapDispatch.h

- Remove a couple random spaces in the Python file
- Add cases to the argument parsing logic to handle forwrad-declared struct, e.g. types with `struct` in the modifiers
Resolves #162

Properly handle forward-declared structs

---

src/VkBootstrap.cpp
src/VkBootstrap.h

Add image usage flags to swapchain creation as well as move the Result & Error types out of the detail namespace, putting them in the main vkb namespace.
Also formats to_string functions.

Add Image usage for swapchain & Move vkb::Result out of the detail namespace

---

src/VkBootstrap.h

Android typically only supports the INHERIT bit. Easiest way to accommodate this is to #ifdef ANDROID to use the INHERIT bit.
Fixes #171

Change deafult composite alpha for Android

---

src/VkBootstrap.cpp
src/VkBootstrap.h
tests/bootstrap_tests.cpp

To solve #169, I chose the following approach:
1. Remove default format_feature_flag (set to 0)
2. Enforce checking of user requirements (format features, image usage and desired formats)
3. To check image usage, only basic verification is done, by checking that the usage match the swapchain capabilities (in the usual case of non-shared present modes)
See below some notes on the change to explain the decision:
1. Even _VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BIT_ is not a good default because it implies that the format should support usage _VK_IMAGE_USAGE_INPUT_ATTACHMENT_BIT_, which is not mandatory by the spec (color attachment is the only mandatory usage for implementers).
2. This broke a test on my machine because it doesn't support _VK_FORMAT_R8G8B8A8_UNORM_ as swapchain format. It should …

Stricter verifications in SwapchainBuilder and other default format feature

---

src/VkBootstrap.cpp

Fixed SwapchainBuilder second constructor, which had 'info.graphics_queue_index = present.value()' and 'info.present_queue_index = graphics.value()'.

Fix graphics/present queue assignment

---

script/generate_dispatch.py
src/VkBootstrapDispatch.h

The XML added requirements which had multiple extensions be required. This broke the existing autogen because it assumed there would only be one extension required at a time. The fix is easy, split the requirement string into a list then add it to the list of requirements.

Handle multiple required extensions in generator

---

README.md
src/VkBootstrap.cpp
src/VkBootstrap.h
tests/bootstrap_tests.cpp

If an application uses add_required_extension_features but also adds
a VkPhysicalDeviceFeatures2 to the pNext chain of VkDeviceCreateInfo,
this will now result in an error. The reason is that Vk-Bootstrap is
perfectly capable of adding VkPhysicalDeviceFeatures to the pNext
chain itself but only if the user didn't already add their own.
Fixes #179

Add new error condition for DeviceBuilder

---

CMakeLists.txt

Similar to this: https://github.com/charles-lunarg/vk-bootstrap/issues/165
But to avoid warnings if vk-bootstrap is built from top CMakeLists directly.

Added cmake options to hide warnings if is not main project

---

CMakeLists.txt
example/CMakeLists.txt
ext/CMakeLists.txt

Marks the main vk-bootstrap library as a static library.
Removes unnecessary code, adds a language & description to the project field.

Mark vk-bootstrap as static & cleanup CMake

---

src/VkBootstrap.cpp
src/VkBootstrap.h
tests/bootstrap_tests.cpp

Issue: `vkb::CustomQueueDescription` provides an interface that allows a mismatch between the size priorities vector and the count of queues.  This allows the user to provide a vector that is too small (and have a memory read out of bounds), or allows the user to provide a vector that is larger than the count and expect all elements in the vector to be used.
Solution: To solve this, we break the API.  Instead of consuming both a count and a vector, `vk-bootstrap` will use the size of the vector to determine queue count.  While it's not typically a good thing to break the API, this provides us a mechanism to make VKB safer with a trivial fix for code consuming this.

Fix API of CustomQueueDescription

---

src/VkBootstrap.h
tests/CMakeLists.txt

The ability to request that some physical device or swapchain has certain features but not require said features leads to confusion due to users having to manually check if any desired request succeeded or not. Thus, this feature is being deprecated, with eventual removal in the future.

Add deprecation notice to "desired" requests

---

src/VkBootstrap.cpp
src/VkBootstrap.h
tests/bootstrap_tests.cpp

Convenience function to check if a given extension would be enabled on the physical device.
Fixes #199

Add PhysicalDevice::is_extension_present()

---

src/VkBootstrap.cpp
src/VkBootstrap.h
tests/bootstrap_tests.cpp

If the given extension is present, enable_extension_if_present will make the extension be enabled on the device.
This fixes a gap in capability due to the deprecation of add_desired_extension.

Add enable_extension_if_present to vkb::PhysicalDevice

---

script/generate_dispatch.py
src/VkBootstrapDispatch.h
tests/CMakeLists.txt
tests/include_checks.cpp

Generator script was missing a case - causing incorrect code gen resulting in a compiler errror for wayland.

Fix wrong parameter in Wayland function

---

src/VkBootstrap.h

Fixes issues putting VkBootstrap.h into modules.
Fixes #195

Mark QUEUE_INDEX_MAX_VALUE as inline

---

src/VkBootstrap.h

Turns out that was me being over eager in removing anything with 'desire' in the name, and that for Swapchains there is a direct way to see the properties of the swapchain after its creation, as vkb::Swapchain contains image count, colorspace, present mode, and many other properties.

Remove deprecation notice in SwapchainBuilder

---

src/VkBootstrap.cpp

Removes the subclassing of VulkanLibrary, bringing its logic into the VulkanFunctions class. This resolves a weird linking issue which was causing hot-reloading of shared libraries that statically linked vk-bootstrap to fail to unload correctly, preventing reloading.
The commit also consolidates the logic in load_vulkan_funcs() into a single function rather than having it be split in three, which only made the code harder to reason about.
Also made vk-bootstrap look for `libMoltenVK.dylib` on apple platforms, in case the application only has the MoltenVK shared library but not the loader (and the user didn't manually load GetInstanceProcAddr from MoltenVK then give it to vk-bootstrap).

Cleanup internal class VulkanFunctions

---

src/VkBootstrap.cpp
src/VkBootstrap.h

The instance & physical device selector only allowed adding a single extension at a time. This commit adds overloads for a vector of const char*'s and a count + pointer pair.
Fixes #224

Add size + ptr & vector overloads for add_extensions

---

CMakeLists.txt
example/CMakeLists.txt
ext/CMakeLists.txt
tests/CMakeLists.txt
tests/integration/CMakeLists.txt
tests/integration/integration_test.cpp
tests/vulkan_mock.hpp

Adds extensive integration tests that exercise the various ways of finding
the Vulkan-Headers.
vk-bootstrap should now use the Vulkan-Headers or Vulkan::Headers targets if
they were already defined (such as is the case of FetchContent), and will
look for the VulkanHeaders package and Vulkan package as a fallback, and will
FetchContent Vulkan-Headers directly if that fails.
This should make integration seamless with the various ways vulkan-headers
is acquired.
The vk-bootstrap-vulkan-headers target was dropped in favor of directly
linking to Vulkan-Headers (creating a target by that name if none exists).
Update to GLFW 3.3.8 in example code

Cleanup CMake finding of Vulkan & installation code 

---

script/generate_dispatch.py
src/VkBootstrapDispatch.h

Types that are promoted get turned into aliases, but the dispatch table was missing these types. This was due to a simple mistake of mixing up the alias with the type being aliased.
Fix #207

Fix aliased types not being generated

---

script/generate_dispatch.py
src/VkBootstrapDispatch.h

Generalize the mechanism to not enable function pointers based on the current header version, due to VK_EXT_discard_rectangles adding functions not present in the original extension.

Workaround VK_EXT_discard_rectangles adding new functions

---

script/generate_dispatch.py
src/VkBootstrapDispatch.h

vkCmdSetExclusiveScissorEnableNV was added to an existing extension in 1.3.241. Guard it against users with older headers.

Manually guard vkCmdSetExclusiveScissorEnableNV

---

script/generate_dispatch.py
src/VkBootstrapDispatch.h

This was missing, causing errors in user code due to not preserving const

Add const case to parameter parsing in autogen

---

src/VkBootstrap.cpp
src/VkBootstrap.h
tests/bootstrap_tests.cpp

Vulkan has extensions that require other extensions to be enabled to be used, which can lead to the following case.
I propose a cleaner solution that can test a vector of extensions and enables all of them if they're all present.

Enable Extensions If Present

---

src/VkBootstrap.cpp
src/VkBootstrap.h

This adds `std::move` or explicit references to some places to avoid unnecessary re-allocations for vectors or other objects. I also replaced a `size` check with a `empty` check and replaced one `push_back` with a `emplace_back`, but there's a lot more of those around the codebase.

Fix: Move objects/vectors where applicable

---

src/VkBootstrap.h

A dangling reference will apear in the following code:
`
for(auto view : vkb_swapchain.get_image_views().value())
{
//Anything
}
`
Returning an rvalue reference binding the subobject of a tempory object doesn't make any sense.
Please see [this](https://stackoverflow.com/questions/27368236/return-value-or-rvalue-reference) for more details.
There is a simple example: [https://godbolt.org/z/YcEefWGr7](https://godbolt.org/z/YcEefWGr7)

Fix: dangling reference in the range-based for loop

---

CMakeLists.txt

While vk-bootstrap is a static library, it needs to have PIC enabled if BUILD_SHARED_LIBS is on so it can work with shared libraries.

Enable PIC if BUILD_SHARED_LIBS is on

---

docs/getting_started.md
src/VkBootstrap.cpp
src/VkBootstrap.h
tests/CMakeLists.txt
tests/bootstrap_tests.cpp
tests/vulkan_mock.cpp
tests/vulkan_mock.hpp

Allows users to enable features if they are present, getting back a bool telling them whether the feature is supported and will be enabled on the device.
Fixes #269

Add enable_features_if_present to PhysicalDevice

---

src/VkBootstrap.cpp

This is a draft workaround for the problem mentioned in #282 
The changes include:
-Turn every argument in `support_features` into const pointers.
-Change `support_fueatures` calls to match the new arguments.
-Add checks for `nullptr` in `support_features`.

[Draft] [Work Around] Fix Segmentation Fault in supports_features Function

---

src/VkBootstrap.cpp
src/VkBootstrap.h
tests/bootstrap_tests.cpp

Features 11, 12, and 13 structs used to set the sType manually for the user. That was turned into an assert which inadvertently broke users code. This is being reverted.

Set the sType for users to fix regression

---

src/VkBootstrap.cpp
src/VkBootstrap.h
tests/bootstrap_tests.cpp

Add `are_extension_features_present` to `PhysicalDevice`

---

src/VkBootstrap.h
tests/CMakeLists.txt
tests/bootstrap_tests.cpp
tests/vulkan_hpp_tests.cpp
tests/vulkan_mock.hpp
tests/vulkan_mock_setup.cpp
tests/vulkan_mock_setup.hpp

The add_required_extensions_features function is templated, allowing both
vulkan.h and vulkan-hpp types to be passed in. Due to recent changes in
the generic features struct code, this stopped working. By casting the
sType explicitely using static_cast, it restores usage of vulkan-hpp types.
Since the API can accept vulkan-hpp types in a few places, it is good to have
tests for those places. While the current test suite isn't exhaustive, it is
enough to get the ball rolling.
This PR also refactors some of the 'setup' logic for the tests into a separate
file so that the hpp tests can make use of them.

static_cast the sType to allow Vulkan-Hpp types to work 

---

src/VkBootstrap.cpp
src/VkBootstrap.h

Make the API take the struct by const reference by creating a local variable that copies the struct, allowing the sType to be set correctly.
The need to set the sType is due to a deficiency in the first version of these functions, which allows users to not set the sType. Making users set the sType is difficult because it breaks user code without warning upon updating the version of vk-bootstrap used.

Make PhysicalDeviceSelector::set_require_featurs_1_X const

---

src/VkBootstrap.cpp

This method should call vkGetPhysicalDeviceFeatures2KHR on Vulkan 1.0.

Fix enable_extension_features_if_present on Vulkan 1.0

---

.github/workflows/run_autogen.yml

Setting up tokens is necessary to allow github to run CI on pull requests made automatically - this wasn't the case when the autogen code was added but is probably a good thing for security reasons.

Use token in run_autogen.yml to enable CI being run

---

script/generate_dispatch.py
src/VkBootstrapDispatch.h

Header update 1.3.298 changed the definition of functions. Should have caught this during the PR review, as well better late than never.

Add AMDX functions to header version workaround list

---

.github/workflows/ci_build.yml

Prevents ci from being run on branches that have a PR created for them. This doesn't prevent ci from running on PR's from forks.

Don't run ci twice on PR's

---

script/generate_dispatch.py
src/VkBootstrapDispatch.h

The vulkan spec updated to include depends="" attributes in the requires blocks of extensions. The autogen needed to be updated to use that as that is the correct mechanism to ascertain which functions require more than one extension to be present. This also required refactoring the logic to respect that.

Use depends attr in xml to generate correct macro defines

---

src/VkBootstrap.h

The sentinel value `QUEUE_INDEX_MAX_VALUE` has been introduced in this https://github.com/charles-lunarg/vk-bootstrap/commit/41203627624b3c21c6cc3e134a73927a17b025f0 commit. Its value 65536 looks confusing to me because the maximum value of `uint32_t` is 4294967295. And I suggest to use an already used in `VkBootstrap.cpp` macro `UINT32_MAX` instead of a magic number 4294967295.

Use UINT32_MAX instead of 65536 for QUEUE_INDEX_MAX_VALUE

---

src/VkBootstrap.cpp

The other destroy functions have this, seem to just be an oversight it is missing for `vkDestroyDevice`

Check for null device before destroying

---

src/VkBootstrap.cpp
src/VkBootstrap.h

Fixes https://github.com/charles-lunarg/vk-bootstrap/issues/332.

Type fixes

---

README.md
example/CMakeLists.txt
example/basic_usage.cpp

1. Reduce the `README.md` example to be simpler (and show how simple it is)
2. Move the comments and actual "basic usage" details to a `basic_usage.cpp` file

Move README example to basic_usage.cpp

---

tests/vulkan_mock_setup.cpp

_DIRECT2DISPLAY path probably is not fully supported yet, but this resolves an invalid `VK_KHR_android_surface` usage issue for mock test setup.

Use display extension on DIRECT2DISPLAY

---

src/VkBootstrap.cpp
src/VkBootstrap.h
tests/bootstrap_tests.cpp

The `desired_<foo>` API functions created ambiguity in what the actual capabilities of a VkInstance and VkDevice were, and thus were deprecated. Since it has been ~2 years from marking them as deprecated, the functions can now be removed.
Note that while the device suitability parameter in physical device selection is removed, the internal logic remains due to the usefulness in moving discrete GPU's to the top of the list and integrated after.

Remove deprecated functions

---

docs/getting_started.md
example/basic_usage.cpp
src/VkBootstrap.cpp
src/VkBootstrap.h
tests/bootstrap_tests.cpp
tests/vulkan_hpp_tests.cpp
tests/vulkan_mock_setup.cpp
tests/vulkan_mock_setup.hpp

Add SystemInfo::is_instance_version_available
Better document InstanceBuilder::set_minimum_instance_version

Add SystemInfo::iis_instance_version_available, Better document set_minimum_instance_version

---

src/VkBootstrap.h

This lets users query this before making a device, which might be needed to make decisions on extensions / features.

Make instance and api versions public in Instance

---

src/VkBootstrap.cpp
src/VkBootstrap.h

This adds support for specifying Vulkan 1.4 features when selecting a physical device. Tested locally in my hobby renderer

Add VK 1.4 features

---

src/VkBootstrap.h

Fixes https://github.com/charles-lunarg/vk-bootstrap/issues/356.
`destroy()` calls are needed in `Result& operator=(Result const& result)` and `Result& operator=(Result&& result)` because assignment operators, in contrary to constructors, are called for already constructed objects. Constructed objects may have allocated memory that is needed to be freed by calling `destroy()` before proceeding.
You may observe such approach inside other assignment operators: `Result& operator=(const T& expect)`, `Result& operator=(T&& expect)`, `Result& operator=(const Error& error)`, `Result& operator=(Error&& error)`. They all have `destroy()` call in the beginning.

Eliminate memory leaks inside Result

---

.github/workflows/ci_build.yml
CMakeLists.txt
tests/CMakeLists.txt
tests/bootstrap_tests.cpp
tests/vulkan_mock.cpp
tests/vulkan_mock.hpp
tests/vulkan_mock_setup.cpp
tests/vulkan_mock_setup.hpp

* Adds ENABLE_ADDRESS_SANITIZER for testing and enables it in CI
* Fix issues in tests found by ASAN
* Make VulkanMock independent from vk-bootstrap (was only needed for the feature struct pNext chain helper)
* Simplify the linux shim - do not need to intercept dlsym, needed for ASAN
* Add a test case for vkb::Result<> so that it has test coverage.

Cleanup Tests & add Address Sanitizer support

---

src/VkBootstrap.cpp

Window's GetProcAddress returns FARPROC, not void*, so needs extra work to cast into the output type safely.

Safely convert return value of GetProcAddress

---

script/generate_dispatch.py
src/VkBootstrapDispatch.h

As a quick fix, hardcode the original types in promoted commands so that users can use newer vk-bootstrap with older headers.

Add hardcoded de-promotion logic to codegen

---

script/generate_dispatch.py
src/VkBootstrapDispatch.h

Promoted commands, like EXT to KHR, still exist and can be used. However, their parameters use the promoted types, not the original types. EG, vkFooEXT(VkBarKHR). This is problematic as vk-bootstrap can't be certain of the header version it is compiled against. Being able to use a new vk-bootstrap with old headers is a boon, and so making sure type definitions that for promoted-from types still work is important.
To do that requires iterating though all aliases, generating a map to go from promoted type to the alias, and then applying this map over the parameters of commands which need it. Ideally, this info is available in vulkan object directly, but it currently does not.

Automate handling of promoted commands

---

src/VkBootstrap.cpp
tests/bootstrap_tests.cpp
tests/vulkan_hpp_tests.cpp
tests/vulkan_mock.cpp
tests/vulkan_mock.hpp

Adds missing logic to handle when set_minimum_instance_version is called but require_api_version isn't. 
Now correctly logs error messages when set_minimum_instance_version results in an instance version error.
Adds tests to check the validity of set_minimum_instance_version.

Handle when minimum_instance_version is set but required_api_version isn't

---

src/VkBootstrap.cpp

Addresses https://github.com/charles-lunarg/vk-bootstrap/issues/419.
I let mutexes live in their scopes at `deinit_all` to prevent any possible deadlock scenario.

Rework deinitialization

---

src/VkBootstrap.cpp
tests/bootstrap_tests.cpp
tests/vulkan_mock.cpp
tests/vulkan_mock.hpp

Add a simple test to ensure that all images are cleaned up. Not a perfect test, but is easy enough to verify the function was called enough times.

Cleanup image views in error path

---

src/VkBootstrap.cpp
tests/bootstrap_tests.cpp

commit 6a458fa broke the logic to move a physical device with the preferred device type to the front of the list.
This fixes that mistake and adds tests to prevent it from occurring again.

Fix broken device type selection

---

src/VkBootstrap.h

Here in `src/VkBootstrap.h`
```
/* If headless mode is false, by default vk-bootstrap use the following logic to enable the windowing extensions
#if defined(_WIN32)
VK_KHR_win32_surface
#elif defined(__linux__) || defined(__FreeBSD__)
VK_KHR_xcb_surface
VK_KHR_xlib_surface
VK_KHR_wayland_surface
#elif defined(__APPLE__)
VK_EXT_metal_surface
#elif defined(__ANDROID__)
VK_KHR_android_surface
#elif defined(_DIRECT2DISPLAY)
VK_KHR_display
#endif
Use `InstanceBuilder::enable_extension()` to add new extensions without altering the default behavior
Feel free to make a PR or raise an issue to include additional platforms.
*/
```
I spotted that `__linux__` is checked before `__ANDROID__`. I expect that `__linux__` is defined on Android. So `__ANDROID__` should be checked before `__linux__`. …

Make order of platforms in comments correct and aligned with InstanceBuilder::build()
