- docs/getting_started.md
- example/triangle.cpp
- src/VkBootstrap.cpp
- src/VkBootstrap.h
- tests/CMakeLists.txt
- tests/bootstrap_tests.cpp
- tests/error_code_tests.cpp
Address #24.
**Warning**: API break
> Error handling with std::error_code

- .clang-format
- src/VkBootstrap.cpp
- src/VkBootstrap.h
Specifically these issues
Fixes #36 
Fixes #40 
Fixes #41 
Fixes #42
Also rewrote queue handling to use uint32_t everywhere with an added QUEUE_INDEX_MAX_VALUE as a sentinel. Removes excessive casting.
> Address several issues in one fell swoop

- src/VkBootstrap.cpp
- src/VkBootstrap.h
- tests/bootstrap_tests.cpp
Reverts charles-lunarg/vk-bootstrap#59
> Revert "Added generic feature polling/enabling."

- .github/workflows/ci_build.yml
- CMakeLists.txt
- README.md
Revert the revert, for I have reverted the wrong revert....
Reverts charles-lunarg/vk-bootstrap#62
> Revert "Revert "CMake: add an option to enable warnings as errors""

- src/VkBootstrap.cpp
- src/VkBootstrap.h
- tests/bootstrap_tests.cpp
Reverts charles-lunarg/vk-bootstrap#63
Now that CI is running, should be able to find the Ubuntu errors and fix them.
> Restart Added generic feature polling/enabling

- src/VkBootstrap.cpp
> Right test in SystemInfo constructor

- example/triangle.cpp
- src/VkBootstrap.cpp
- src/VkBootstrap.h
- tests/bootstrap_tests.cpp
- tests/common.h
Also updates the sample code and tests to use this functionality.
> Add `vkb::destroy_surface` helper function

- src/VkBootstrap.cpp
- src/VkBootstrap.h
> Replacing reinterpret_cast with memcpy.

- .github/workflows/ci_build.yml
Rely on CMake's FetchContent to get the required headers
> Update actions to remove SDK/headers downloads

- src/VkBootstrap.cpp
- tests/bootstrap_tests.cpp
Also cleanup some warnings in the tests.
Fixes #131
> Support VK_KHR_portability_enumeration

- src/VkBootstrap.cpp
- src/VkBootstrap.h
Hi,
This is a suggested fix for [#137](https://github.com/charles-lunarg/vk-bootstrap/issues/137).
I'm open to any feedback.
> SwapchainBuilder: provide some control over minImageCount

- docs/getting_started.md
my first issue, just ran into this while trying it out myself
Is this the correct way to do this?
> :: instead of . required

- .clang-format
- src/VkBootstrap.cpp
- src/VkBootstrap.h
Modify the .clang-format to format with spaces for indention instead of tabs
> Use spaces instead of tabs

- src/VkBootstrap.h
> Fix missing return *this in Result class

- .github/workflows/ci_build.yml
- .github/workflows/create_tag.yml
Workflow is triggered manually in order to allow for me to review the PR first.
> Add workflow to tag header updates

- src/VkBootstrap.h
Prevents shadowing warnings from annoying users.
Fixes #280
> Rename parameter in enable_extension_features_if_present

- docs/getting_started.md
> Fix Class typo in getting stared

- src/VkBootstrap.cpp
Addresses https://github.com/charles-lunarg/vk-bootstrap/issues/330.
> Remove auto propagation of allocation callbacks from Device to SwapchainBuilder

- src/VkBootstrap.cpp
- src/VkBootstrap.h
- tests/include_checks.cpp
- tests/vulkan_library_loader.hpp
- tests/vulkan_mock.cpp
- tests/vulkan_mock_setup.cpp
This PR adds support for FreeBSD platforms.
> FreeBSD: Introduce support for FreeBSD

- src/VkBootstrap.cpp
- src/VkBootstrap.h
Fixes https://github.com/charles-lunarg/vk-bootstrap/issues/334.
> Fix GenericFeaturesPNextNode fields array initialization

- src/VkBootstrap.cpp
- src/VkBootstrap.h
Forgot to do that during the 1.3 & 1.4 release...
> Add 1.3 and 1.4 version error codes.

- docs/getting_started.md
- example/CMakeLists.txt
- example/system_info.cpp
closes https://github.com/charles-lunarg/vk-bootstrap/issues/346
> Improve Getting Started doc

- src/VkBootstrap.h
Fixes https://github.com/charles-lunarg/vk-bootstrap/issues/353.
> Eliminate double destruction of m_value

- example/CMakeLists.txt
- example/triangle.cpp
triangle example not foud shader file
> fix triangle example not found shaders

- .github/workflows/ci_build.yml
Fixes https://github.com/charles-lunarg/vk-bootstrap/issues/407.
> Specify compilers in CI

- docs/getting_started.md
Fixes https://github.com/charles-lunarg/vk-bootstrap/issues/399.
> Fix syntax error in getting_started.md
